language: go

go:
  - 1.8

services:
  - docker

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

jobs:
  include:
  - stage: build
    script: make k8s-aws-elb-tagger-all
  - stage: test
    script: make test
