apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-aws-elb-tagger
  labels:
    app: k8s-aws-elb-tagger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-aws-elb-tagger
subjects:
  - kind: ServiceAccount
    name: k8s-aws-elb-tagger
